### ISSUE TITLE
Feature: Add Community Translations Section

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/intro#71] opened 2023-10-10 16:43 UTC
### Type of feature

🍕 Feature

### Current behavior

Although it's not possible for OpenSauced to create and maintain all requested translations, we value community translation contributions.

To recognize these contributions but also let our users know that we are not specifically maintaining them, we are creating a file for contributors to link to their translations.

To do this, there are two steps:
1. Create `community-translations.md` at the root of the repo. In that file, Create the following:
```
# Community Course Translations
We are grateful for the contributions of the community in translating this course. Although the OpenSauced team does not currently maintain these projects, we want to share the forked copy of the repositories with those taking the course. Below, you will find the latest community translations.
```
3. In the README in "Additional Information" section, add a bullet point that links to `community-translations.md`, next to the link, it should say that these translations are not maintained by OpenSauced, but we welcome contributors to link their forked translations.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by a-ridley** [comment] 2023-10-11 00:44
Hello 👋, new to Open Sauced and looking to contribute with a Spanish translation. :)

I was curious instead of creating a file for community translations, if a community translations section can be added below the Language Support section instead? It would allow people visiting the repo to find their translation section without having navigate and find the file, click, and then find their language. 

I believe this would provider easier access. :)

**Comment by CBID2** [comment] 2023-10-11 03:35
> Hello 👋, new to OpenSauced and looking to contribute with a Spanish translation. :)
> 
> I was curious instead of creating a file for community translations, if a community translations section can be added below the Language Support section instead? It would allow people visiting the repo to find their translation section without having navigate and find the file, click, and then find their language.
> 
> I believe this would provider easier access. :)

Hi @a-ridley! :) I'm currently in the process of creating a translation guide, so [subscribe here](https://github.com/open-sauced/guestbook/pull/116) to get updates on it

**Comment by CBID2** [comment] 2023-10-30 20:19
> Hello 👋, new to OpenSauced and looking to contribute with a Spanish translation. :)
> 
> I was curious instead of creating a file for community translations, if a community translations section can be added below the Language Support section instead? It would allow people visiting the repo to find their translation section without having navigate and find the file, click, and then find their language.
> 
> I believe this would provider easier access. :)

Hey @a-ridley! :) The translation guidelines are now up. Check them out here: https://github.com/open-sauced/intro/blob/main/i18n-guidelines.md

**Comment by antonio-pedro99** [comment] 2024-01-06 14:39
@BekahHW @CBID2 I was thinking, adding a list of words we don't need to translate would make the translations more consistent. 

I would be happy contributing by compiling a list of open-source terms translators do not need to translate to their language while translating…
Some words can be `merge`, `issue`, `pull request`, `branch` and others.

**Comment by CBID2** [comment] 2024-01-06 16:34
> @BekahHW @CBID2 I was thinking, adding a list of words we don't need to translate would make the translations more consistent. 
> 
> 
> 
> I would be happy contributing by compiling a list of open-source terms translators do not need to translate to their language while translating…
> 
> Some words can be `merge`, `issue`, `pull request`, `branch` and others. 

That's a great idea @antonio-pedro99

**Comment by BekahHW** [comment] 2024-01-11 15:06
> @BekahHW @CBID2 I was thinking, adding a list of words we don't need to translate would make the translations more consistent.
> 
> I would be happy contributing by compiling a list of open-source terms translators do not need to translate to their language while translating… Some words can be `merge`, `issue`, `pull request`, `branch` and others.

Love the idea!

**Comment by adiati98** [comment] 2024-01-11 16:19
@BekahHW does this issue related to the [Community Translations](https://github.com/open-sauced/intro/blob/main/i18n-guidelines.md#2-community-translations) section on the `i18n-guidelines.md`?

I think the reason that this issue is not taken yet because there are many open comments here and some are kind of indicating that it's been working on.

What I can suggest:

- Close this issue as "not planned" and start fresh.
- What are stated in the issue is clear enough. But I have a thought for point no. 3:
   
   I like the idea in [this comment](https://github.com/open-sauced/intro/issues/71#issuecomment-1756533448) to group translations in one place. But instead of listing the community translations, we can say something like:

   ```markdown
   ## Language Support

   Like pizza, open source is meant to be shared with everyone. We provide and maintain translations in languages below as our official translations:

   - [French](link)

   For translations in other languages that are maintained by our community, please go to our [Community Translations](link to community-translations.md).
   ```

**Comment by adiati98** [comment] 2024-02-11 21:24
After a discussion with @open-sauced/community team, we will start fresh for this issue.
Therefore, we close this issue. The new issue is linked above.

**Closed by adiati98** 2024-02-11 21:24 UTC
Labels: good first issue, 💡 feature
